Criado Retorno Sicoob padrão CNAB240 - Segmento T e U
manoelcampos/retorno-boletophp pull request #6
Opened 2018-02-15 01:49 UTC by mauroagr

- Foi criado o arquivo de retorno para o Banco SICOOB padrão CNAB240, segmento T e U
- Alguns ajustes de tabulação e espaçamento foram removidos

2018-03-01 12:23 UTC, manoelcampos requested changes
Obrigado pela contribuição. Existem só minimos detalhes que gostaria que corrigisse antes de eu aprovar a PR.

2018-03-01 12:23 UTC, manoelcampos commented on src/ManoelCampos/RetornoBoleto/RetornoCNAB240Sicoob.php
> + * @author <a href="http://manoelcampos.com/contact">Manoel Campos da Silva Filho</a>
Coloque seu nome como autor, afinal de contas foi vc quem fez esta classe.

2018-03-01 12:23 UTC, manoelcampos commented on src/ManoelCampos/RetornoBoleto/RetornoCNAB240Sicoob.php
> +class RetornoCNAB240Sicoob extends RetornoAbstract {
A classe deveria estender RetornoCNAB240.

2018-03-01 12:23 UTC, manoelcampos commented on src/ManoelCampos/RetornoBoleto/RetornoCNAB240Sicoob.php
> +    public function getTotalCaracteresPorLinha() {
Estendendo RetornoCNAB240, alguns métodos como este não precisam ser redefinidos.

2018-03-03 13:55 UTC, mauroagr commented
Manoel, 
Alterações feitas.
abraço
Mauro

2018-03-14 14:04 UTC, manoelcampos approved these changes
Feita apenas uma alteração no método `tentaInstanciarCnab240()`. Veja mensagem do commit para detalhes.

Obrigado pela contribuição.

2018-03-14 14:04 UTC, merged